### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by psychon** [psychon/as-raw-xcb-connection#1]
Hi @rtbo @eduardosm @notgull

I started this crate due to https://github.com/rust-x-bindings/rust-xcb/issues/217. The plan is to get this into shape and then release version 1.0 of this crate. I already started and wrote down a suggestion on how this could look like. For those who hear about this the first time: I suggest to use this experience to figure out whether reading https://github.com/psychon/as-raw-xcb-connection/blob/main/src/lib.rs is self-explanatory. ;-)

I picked you as a "random collection of people who might be interested in this crate". If you think the state of this is fine, just say so. If not, say so and/or open PRs. If everyone is fine with the state of this crate, I'd release version 1.0 and start trying to get it into the ecosystem by spamming PRs everywhere.

**Comment by notgull** [comment]
Looks good to me. I like that you solve the problem that `raw-window-handle` has and explicitly say that the connection has to live as long as the object does.

The only thing I'd do is add an object which wraps a raw `xcb_connection_t` pointer and has an unsafe constructor, to act as an escape hatch for when you have a raw pointer.

**Comment by psychon** [comment]
> The only thing I'd do is add an object which wraps a raw xcb_connection_t pointer and has an unsafe constructor, to act as an escape hatch for when you have a raw pointer.

Hm? Why? How/why would one use that? Since I do not want to link against libxcb here, this would require to never free the `xcb_connection_t*`...

<details><summary>And does the following count as also satisfying that request? (But this violates the safety invariants...)</summary>
```
diff --git a/src/lib.rs b/src/lib.rs
index 1507df6..4846e98 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -30,3 +30,9 @@ pub unsafe trait AsRawXcbConnection {
     /// Get a raw xcb connection pointer from this object.
     fn as_raw_xcb_connection(&self) -> *mut xcb_connection_t;
 }
+
+unsafe impl AsRawXcbConnection for *mut xcb_connection_t {
+    fn as_raw_xcb_connection(&self) -> *mut xcb_connection_t {
+        *self
+    }
+}
```
(I think this does even uphold half the safety invariant: As long as the `*mut xcb_connection_t` is valid, the returned pointer will be valid. That's trivial. But the other half is broken: This does not ensure that the pointer is valid...)
</details>
Depending on the possible use for that, I'd say whichever crate needs this should implement it itself. Would that be okay?

**Comment by notgull** [comment]
I was thinking more in the vein of #2.

**Comment by rtbo** [comment]
Hi, Thanks @psychon.
It looks good to me.
