### ISSUE TITLE
Generic event interface

### ISSUE THREAD

**Issue by notgull** [psychon/as-raw-xcb-connection#4]
When it comes to toolkits like XIM, it becomes necessary to also pass events through a "filter" function. This crate may want to provide a trait for X11 events, perhaps providing a way to get the event's bytes, the type of the event, and potentially other important info. However, it may be out of scope.

**Comment by psychon** [comment]
First reaction: There is not much interaction with `AsRawXcbConnection` for that, so I guess that should rather be something else.

Also, just getting the raw bytes of events is not that useful often. One also needs some `QueryExtension` reply infos to figure out even bytes... dunno...

**Comment by notgull** [comment]
I think you're right. I'll close this issue for now.
